### ISSUE TITLE
[UI] As a logged in user, I can see the complete survey screen

### ISSUE THREAD

**Issue by chiiida** [llleyelll/ic-surveys-ios#19]
## Why

- Show complete survey screen when the user complete survey
 
## Acceptance Criteria

- Show a confetti animation when the user complete the survey.
- Show a confetti animation for about 3 seconds and then dismiss.
<img width="290" alt="Screen Shot 2021-06-04 at 9 41 17 AM" src="https://user-images.githubusercontent.com/45258998/120737845-05f92380-c519-11eb-969f-de2c11362525.png">

**Comment by sleepylee** [comment]
don't forget that you will need to make a confetti animation here as well 🎉 🎊

**Comment by chiiida** [comment]
@sleepylee I updated the ticket. Thank you 😊
